import argparse,csv,hashlib,json,math,platform
from pathlib import Path
R15='7ca39facf83de619db7ec37daa90409834d89b4b75bfeb4e7c501ddef94b2ac4'; R16='1b1c3132b44a542605b19f354a5d9c7464a093aa4cb23b04583ca92e0841ec67'
def write(p,x): p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def mem(q):
    l=math.log10(16)+q*math.log10(2); return {'q':q,'amplitudes':f'2^{q}','log10_bytes':l,'bytes_scientific':f'1.6e{l-1:.3f}','GiB_log10':l-math.log10(2**30),'TiB_log10':l-math.log10(2**40),'PiB_log10':l-math.log10(2**50)}
def route(n):
    P=2*n+3; N=n+2; a=(P-1)*N*(N-1); node=P*N; primary=node+P+P+n+a; arc=N*(N-1); order=N*math.ceil(math.log2(P)); at=arc+order+n+1
    return {'n':n,'positions':P,'nodes_including_depot_charger':N,'position_indexed_primary':primary,'position_indexed_auxiliary':0,'position_indexed_total':primary,'position_indexed_quadratic_estimate':2*a+2*node+P*N,'arc_based_primary':at,'arc_based_auxiliary':0,'arc_based_total':at,'arc_based_quadratic_estimate':2*arc+N*order,'scaling_order':'position O(n^3); arc/order O(n^2 log n)'}
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--r15',required=True); ap.add_argument('--r16',required=True); ap.add_argument('--r19',required=True); ap.add_argument('--r20',required=True); ap.add_argument('--out',required=True); a=ap.parse_args()
    r15,r16,r19,r20,out=map(Path,(a.r15,a.r16,a.r19,a.r20,a.out)); out.mkdir(parents=True,exist_ok=False); inst=json.load(open(r15/'common_instance.json')); r20s=json.load(open(r20/'qubo_formulation_spec.json')); r19s=json.load(open(r19/'independent_validation_summary.json'))
    meta={'purpose':'temporary_qiskit_aer_and_hybrid_feasibility_diagnostic','status':'TEMPORARY_DIAGNOSTIC','not_authoritative_for_r20_formulation':True,'not_authoritative_for_problem_size_selection':True,'not_authoritative_for_reduced_problem_selection':True,'not_authoritative_for_quantum_architecture_selection':True,'not_authoritative_for_quantum_provider_selection':True}
    hw=dict(meta,host=platform.node(),os=platform.platform(),cpu='AMD EPYC 9684X 96-Core Processor',physical_cores=192,logical_threads=384,ram='1.5 TiB',available_ram='1.4 TiB',swap='8 GiB',gpu='NVIDIA H100 NVL',gpu_count=1,gpu_memory='95830 MiB',cuda_driver='550.163.01',cuda_python='UNKNOWN')
    sw=dict(meta,python='3.11.15',qiskit='NOT_INSTALLED',qiskit_aer='NOT_INSTALLED',qiskit_optimization='NOT_INSTALLED',numpy='2.4.6',scipy='1.15.3',benchmark_executed=False,reason='Qiskit/Aer unavailable; environment changes prohibited')
    write(out/'hardware_manifest.json',hw); write(out/'software_manifest.json',sw)
    methods={m:{'availability':'unavailable','applicability':'not_tested; Qiskit Aer absent'} for m in ['statevector','statevector_gpu','matrix_product_state','tensor_network','density_matrix','stabilizer','extended_stabilizer','unitary']}; methods['stabilizer']['note']='non-Clifford QAOA-like circuits are not generally exact stabilizer workloads'; write(out/'aer_method_availability.json',methods)
    with (out/'theoretical_statevector_memory.csv').open('w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=['q','amplitudes','log10_bytes','bytes_scientific','GiB_log10','TiB_log10','PiB_log10']); w.writeheader(); w.writerows(mem(q) for q in [20,25,30,35,40,50,100,13782])
    write(out/'aer_scaling_benchmark.json',dict(meta,executed=False,requested_qubits=[8,10,12,14,16,18,20,22,24],maximum_successfully_simulated_qubits='UNKNOWN_NOT_MEASURED',maximum_practical_qubits='UNKNOWN_NOT_MEASURED',stop_reason='Qiskit/Aer absent; no install permitted'))
    write(out/'simulator_method_comparison.json',dict(meta,methods=methods,comparison_caveat='method presence and QAOA suitability are distinct'))
    est=[route(n) for n in [3,4,5,6,8,10,15,20]]; write(out/'route_order_variable_estimate.json',route(10)); write(out/'route_order_scaling.json',est)
    hcs=[('HC01','SHARED'),('HC02','QUANTUM_ENCODED'),('HC03','QUANTUM_ENCODED'),('HC04','QUANTUM_ENCODED'),('HC05','QUANTUM_ENCODED'),('HC06','CLASSICAL_STATE_PROPAGATION'),('HC07','CLASSICAL_STATE_PROPAGATION'),('HC08','CLASSICAL_STATE_PROPAGATION'),('HC09','NOT_APPLICABLE_DISABLED'),('HC10','CLASSICAL_STATE_PROPAGATION'),('HC11','CLASSICAL_PREPROCESSING'),('HC12','CLASSICAL_STATE_PROPAGATION'),('HC13','CLASSICAL_PREPROCESSING')]; write(out/'HC_responsibility_matrix.json',[{'HC':h,'temporary_responsibility':r,'note':'candidate only; not formal architecture'} for h,r in hcs])
    write(out/'hybrid_architecture_candidate.json',dict(meta,preprocessing=['reachability','necessary F_ij filter','TW/payload/SOC/charging bounds','infeasible transition elimination'],quantum=['route/order candidate only'],postprocessing=['route/state reconstruction','HC01-HC13 validation','objective/system metrics'],F_ij='necessary-condition filter, not sufficient for history-dependent full-route feasibility',unresolved=['scope','discretization','provider','queue/error/cost']))
    write(out/'end_to_end_runtime_definition.json',dict(meta,T_total='T_pre+T_QUBO+T_map_or_transpile+T_solve+T_post',T_pre='classical preprocessing',T_QUBO='QUBO construction',T_map_or_transpile='mapping/circuit generation/transpile',T_solve='CP-SAT/Aer/QPU',T_post='decode/validation/reconstruction',T_wall_cloud='T_total+T_queue',T_QAOA_total='T_pre+T_QUBO+T_transpile+sum(T_expectation(k))+T_post',expectation='N_iterations*N_expectation_evaluations*shots*per-shot/job cost',queue_separate=True))
    opts=[['Option 1 full classical','SUPPORTED_BY_CURRENT_EVIDENCE'],['Option 2 Hayate+Aer','UNCERTAIN; package unavailable'],['Option 3 Hayate+cloud QPU','PLAUSIBLE_BUT_UNSUPPORTED; provider/QPU evidence absent']]; write(out/'option_comparison.json',dict(meta,options=opts))
    write(out/'diagnostic_conclusions.json',dict(meta,hypothesis_A='PARTIALLY_SUPPORTED_BY_THEORY; width/memory/repeated expectation cost dominate',hypothesis_B='PLAUSIBLE_BUT_UNTESTED; state layer may reduce width',hypothesis_C='PARTIALLY_SUPPORTED_CONCEPTUALLY; hybrid technically discussable',full_13782='statevector impractical; MPS unknown/not generalizable',temporary_boundary='TEMPORARY_HAYATE_DIAGNOSTIC_BOUNDARY_NOT_MEASURED',R20_status_unchanged='BLOCKED',next_allowed_stage_unchanged='NONE'))
    write(out/'manifest.json',dict(meta,run_id=out.name,input_hashes={'r15':R15,'r16':R16,'r19_status':r19s['status'],'r20_status':r20s['status']},R20_status_unchanged='BLOCKED',next_allowed_stage_unchanged='NONE',files={p.name:sha(p) for p in sorted(out.iterdir()) if p.is_file()}))
if __name__=='__main__': main()
