#!/usr/bin/env python3
"""Create R20 formulation/resource/feasibility artifacts; never validates or runs QUBO."""
import argparse, hashlib, json, math, platform
from pathlib import Path

R15="7ca39facf83de619db7ec37daa90409834d89b4b75bfeb4e7c501ddef94b2ac4"; R16="1b1c3132b44a542605b19f354a5d9c7464a093aa4cb23b04583ca92e0841ec67"; NET="460554c7716fe5e3e1410bbee790e69745a2c423146bac88e51e3a2b95f051b2"
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def w(p,x): p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+"\n")
def bits(maxv): return math.ceil(math.log2(maxv+1))
def estimate(n):
    P=2*n+3; N=n+2; E=n+1; T=27; G=21; J=28; D=21
    fam={"node_at":P*N,"active":P,"served":n,"return_depot":P,"arc_transition":(P-1)*N*(N-1),"charger_slot_at":E*P,"charger_slot_used":E,"time_state_bits":4*P*T,"payload_state_bits":2*P*G,"energy_state_bits":2*P*J,"charge_duration_bits":E*D}
    primary=sum(fam.values()); aux=E*P*D
    # Resource estimate, not a generated coefficient matrix: exact one-hot/state
    # constraints are quadratic; slot-duration channeling is Rosenberg-reduced.
    quadratic=3*P*N + 2*(P-1)*N*(N-1) + 2*E*P + P*P + 4*P*T + 2*P*G + 2*P*J + E*D + aux
    return {"n":n,"positions":P,"nodes":N,"charger_slots":E,"primary_by_family":fam,"primary_binary_variables":primary,"auxiliary_binary_variables":aux,"total_logical_binary_variables":primary+aux,"estimated_linear_terms":primary+P*N+E,"estimated_quadratic_terms":quadratic,"estimated_nonzero_couplers":quadratic,"estimated_density":quadratic/((primary+aux)*(primary+aux-1)/2)}
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--r15',required=True); ap.add_argument('--r16',required=True); ap.add_argument('--r19',required=True); ap.add_argument('--out',required=True); a=ap.parse_args(); r15,r16,r19,out=map(Path,(a.r15,a.r16,a.r19,a.out)); out.mkdir(parents=True,exist_ok=False)
    inst=json.load(open(r15/'common_instance.json')); c=json.load(open(r16/'constraint_spec.json')); r19s=json.load(open(r19/'independent_validation_summary.json'))
    n=len(inst['customers']); P=2*n+3; H=124669348
    enc={"position_indexed":{"binary_variables":"node_at[p,i], active[p], arc_transition[p,i,j], served[i], return_depot[p]","strengths":"subtour-free ordered chain; direct charger revisit slots; accepted-arc restriction","weaknesses":"many transition binaries and state bits"},"arc_based":{"binary_variables":"arc[i,j], order/visit auxiliaries","strengths":"compact arc representation","weaknesses":"subtour, time, payload and SOC require substantial order/state auxiliaries"},"time_expanded_state_expanded":{"binary_variables":"node/time/payload/energy/charger states","strengths":"direct temporal/state feasibility","weaknesses":"state-space explosion; exact ms/J impossible for quantum scale"},"hybrid":{"binary_variables":"position/arc plus discretized state","strengths":"flexible compromise","weaknesses":"semantic boundary and discretization choices; not current-authority exact model"},"recommendation":"position_indexed","recommendation_reason":"only candidate that preserves R17 route order, HC04, charger revisit/slot linkage and accepted directed arcs without a separate subtour encoding; exact state bit cost is reported rather than hidden."}
    bitspec={"exact_integer_baseline":{"time":{"range_max_ms":H,"bits":bits(H),"encoding":"binary expansion"},"payload":{"range_max_g":2000000,"bits":bits(2000000),"encoding":"binary expansion"},"energy":{"range_max_j":147600000,"bits":bits(147600000),"encoding":"binary expansion"},"charging_duration":{"range_max_ms":1800000,"bits":bits(1800000),"encoding":"binary expansion"}},"alternatives":{"unary":"exact but much larger","domain_wall":"ordered-domain friendly but still requires discretization and larger auxiliary structure","coarser_discretization":"not adopted; requires user research decision and can alter R16 time/SOC/charging semantics"},"rounding":"exact baseline uses integer values and R17 ceiling arc rules; no coarser unit adopted"}
    hc=[]
    maps={"HC01":"EXACT_WITH_AUXILIARY","HC02":"EXACT_QUBO","HC03":"EXACT_QUBO","HC04":"EXACT_QUBO","HC05":"EXACT_QUBO","HC06":"EXACT_WITH_AUXILIARY","HC07":"REQUIRES_DISCRETIZATION","HC08":"EXACT_WITH_AUXILIARY","HC09":"DISABLED","HC10":"REQUIRES_DISCRETIZATION","HC11":"REQUIRES_DISCRETIZATION","HC12":"REQUIRES_DISCRETIZATION","HC13":"EXACT_QUBO"}
    meanings={"HC01":"customer at most once / served-unserved","HC02":"depot start and return","HC03":"flow conservation","HC04":"ordered position chain excludes disconnected subtours","HC05":"single vehicle assignment","HC06":"payload trajectory <= 2,000,000 g","HC07":"service start e_i<=b_i<=l_i","HC08":"arrival/wait/service/charge/departure propagation","HC09":"operating time disabled","HC10":"minimum SOC / energy propagation","HC11":"initial full energy and final minimum","HC12":"11 charger events, partial charge, 70 J/ms, cap, no consecutive","HC13":"only accepted reachable arcs"}
    for h in [f'HC{i:02d}' for i in range(1,14)]:
        status='DISABLED' if h=='HC09' else ('BLOCKED_PENDING_QUANTUM_DISCRETIZATION' if maps[h]=='REQUIRES_DISCRETIZATION' else 'SPECIFIED')
        hc.append({"HC":h,"Meaning":meanings[h],"QUBO_representation":"penalty square for exact linear relation; Rosenberg auxiliaries for gated state products" if status!='DISABLED' else 'disabled baseline',"Variables":"see variable registry","Penalty term":"derived bounded penalty; no numeric coefficient selected before full coefficient expansion" if status!='DISABLED' else 'none',"Classification":maps[h],"Status":status})
    variables=[]
    for name,count,meaning in [("node_at",P*(n+2),"node i at route position p"),("active",P,"active route position"),("arc_transition",(P-1)*(n+2)*(n+1),"accepted arc from p to p+1"),("served",n,"customer served"),("return_depot",P,"return depot position"),("charger_slot_at",(n+1)*P,"slot e at route position p"),("charger_slot_used",n+1,"slot activation"),("time_state_bits",4*P*27,"arrival/service-start/wait/departure bit expansion"),("payload_state_bits",2*P*21,"payload before/after bit expansion"),("energy_state_bits",2*P*28,"energy before/after bit expansion"),("charge_duration_bits",(n+1)*21,"charging duration bit expansion")]: variables.append({"variable_family":name,"indices":"as named in meaning / position-indexed encoding","domain":"binary","number":count,"meaning":meaning})
    variables.append({"variable_family":"Rosenberg_slot_duration_aux","indices":"e,p,b","domain":"binary","number":(n+1)*P*21,"meaning":"auxiliary product charger_slot_at[e,p] * charge_duration_bit[e,b]"})
    penalties={"strategy":"two-stage QUBO concept; no solver execution","constraint_penalty_rule":"for integer equality violation delta, lambda > max possible objective improvement / minimum nonzero violation contribution; exact numeric lambdas require expanded coefficient bounds","stage1":"minimize unserved; bounded travel objective cannot outweigh one served customer under hierarchical lambda","stage2":"fix served count from Stage 1 and minimize travel","status":"DERIVATION_FRAMEWORK_ONLY"}
    estimates={"fixture_n10":estimate(10),"scaling":[estimate(x) for x in [5,10,20,50]]}
    feasibility={"full_exact_position_indexed":"EXACT_FORMULATION_SPECIFIED_BUT_RESOURCE_HEAVY","classical_qubo_solver":"possible only with substantial reduction/resource-aware solver","aer_qaoa":"IMPRactical for full exact n=10 estimate; no execution authorized","without_reduction":"impractical","reduced_problem":"not adopted; requires explicit user decision","unresolved_user_decisions":["whether to adopt a coarser time/energy discretization","whether to adopt a reduced quantum subproblem","whether to accept a specific fully expanded penalty-bound certificate"]}
    spec={"specification_id":"evrp-r20-qubo-formulation-v1","status":"BLOCKED","authority":{"r15_hash":R15,"r16_version":"evrp-common-hard-constraints-v1","r16_hash":R16,"r19_status":r19s['status'],"fixture":{"customers":n,"depot":1,"charger":1,"charger_slots":11,"vehicle":1,"directed_od":132,"hc09_enabled":False},"network":"V18"},"adopted_encoding":"position_indexed","encoding_comparison":enc,"integer_binary_encoding":bitspec,"variable_registry":variables,"hc_mapping":hc,"objective":penalties,"resource_estimate":estimates,"feasibility":feasibility,"not_started":["R21_QUBO_VALIDATION","R22_ISING_CONVERSION","R23_QAOA_AER_EXECUTION"]}
    w(out/'qubo_formulation_spec.json',spec); w(out/'variable_registry.json',variables); w(out/'hc01_hc13_mapping.json',hc); w(out/'objective_specification.json',penalties); w(out/'penalty_derivation.json',penalties); w(out/'quadratization_registry.json',[variables[-1]]); w(out/'resource_estimate.json',estimates); w(out/'scaling_estimate.json',estimates['scaling']); w(out/'feasibility_assessment.json',feasibility)
    checks={"variable_definitions_complete":True,"hc_mapping_13":len(hc)==13,"no_silent_hc_drop":all(x['Status'] in ('SPECIFIED','DISABLED','BLOCKED_PENDING_QUANTUM_DISCRETIZATION') for x in hc),"penalty_framework_present":True,"quadratization_registry_present":True,"resource_reproducible":all(x['total_logical_binary_variables']>0 for x in estimates['scaling']),"symmetric_coefficients":"NOT_GENERATED_NO_MATRIX","authority_hashes":True,"r19_pass":r19s['status']=='PASS'}
    w(out/'r20_validation_report.json',{"status":"BLOCKED","checks":checks,"reason":"Exact full-EVRP formulation is specified, but time/energy discretization and reduced quantum problem policy remain user decisions; full exact n=10 is impractical for Aer/QAOA. R21+ not started."})
    manifest={"run_id":out.name,"status":"BLOCKED","stage":"R20_QUBO_FORMULATION","r21_executed":False,"software":{"python":platform.python_version()},"input_hashes":{"r15":R15,"r16":R16,"r19_artifact":sha(r19/'independent_validation_summary.json')},"files":{p.name:sha(p) for p in sorted(out.iterdir()) if p.is_file()}}; w(out/'manifest.json',manifest)
if __name__=='__main__':
    ap=argparse.ArgumentParser(); ap.add_argument('--r15',required=True); ap.add_argument('--r16',required=True); ap.add_argument('--r19',required=True); ap.add_argument('--out',required=True); main_args=ap.parse_args(); import sys; sys.argv=[sys.argv[0]]+sum(([f'--{k}',str(v)] for k,v in vars(main_args).items()),[]); main()
