#!/usr/bin/env python3
"""Create solver-independent R16 hard-constraint semantics."""
from __future__ import annotations
import argparse, json, hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def sha(p):
 h=hashlib.sha256(); h.update(p.read_bytes()); return h.hexdigest()
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--instance',required=True); ap.add_argument('--output-dir',required=True); a=ap.parse_args(); out=Path(a.output_dir); out.mkdir(parents=True,exist_ok=True); instance=Path(a.instance)
 tol={'exact_discrete':{'value':0,'unit':'none','reason':'IDs, assignment, reachability, and enabled flags are exact'},'distance_m':{'value':1e-6,'unit':'m','reason':'floating point path accumulation'},'time_s':{'value':1e-9,'unit':'s','reason':'floating point time propagation'},'energy_kwh':{'value':1e-9,'unit':'kWh','reason':'floating point energy/SOC propagation'},'soc_ratio':{'value':1e-9,'unit':'ratio','reason':'floating point SOC propagation'},'payload_kg':{'value':1e-9,'unit':'kg','reason':'floating point payload accumulation'}}
 def c(i,name,meaning,entities,inputs,unit,enabled,tt,violation,checker,rationale,placeholder): return {'constraint_id':i,'constraint_name':name,'formal_meaning':meaning,'applicable_entity':entities,'required_inputs':inputs,'unit':unit,'enabled':enabled,'judgement':'exact' if tt['value']==0 else 'tolerance_based','tolerance':tt,'violation_condition':violation,'validator_check':checker,'source_rationale':rationale,'downstream_solver_mapping_placeholder':placeholder}
 cs=[
 c('HC01','Customer Visit Constraint','A delivery customer is visited at most once; zero visits are allowed.','customer/route','customer IDs, visit sequence','count',True,tol['exact_discrete'],'visit_count_i > 1','count visits per customer; accept 0 or 1','Plan Common Hard Constraints #1; separates feasibility from DFR objective.','R17/R20 mapping pending'),
 c('HC02','Depot Departure and Return Constraint','Every used vehicle starts at and returns to the single R15 depot.','vehicle/depot','depot ID, route sequence','node ID',True,tol['exact_discrete'],'route start or end is not depot','check first and last route node','R09/R15 depot lock.','R17/R20 mapping pending'),
 c('HC03','Flow Conservation Constraint','For every route node, entries and exits are conserved for the same vehicle.','vehicle/node','route arcs, vehicle IDs','arc count',True,tol['exact_discrete'],'in_count != out_count except route depot balance','recompute per-vehicle node in/out counts','Plan Common Hard Constraints #3.','R17/R20 mapping pending'),
 c('HC04','Subtour Elimination Constraint','A cycle disconnected from the depot is forbidden.','vehicle/route','route arcs, depot','graph',True,tol['exact_discrete'],'cycle component has no depot connection','remove depot and detect route cycles/components','Plan Common Hard Constraints #4.','R17/R20 mapping pending'),
 c('HC05','Vehicle Assignment Constraint','A customer cannot be assigned to more than one vehicle.','customer/vehicle','customer visits, vehicle IDs','assignment count',True,tol['exact_discrete'],'assigned_vehicle_count_i > 1','count distinct vehicles per customer','Plan Common Hard Constraints #5.','R17/R20 mapping pending'),
 c('HC06','Capacity Constraint','Payload on every route segment cannot exceed vehicle payload capacity.','vehicle/route','q_i, payload conversion, capacity','kg',True,tol['payload_kg'],'payload > capacity + tolerance','recompute segment load','R10 payload capacity; no inferred parcel payload beyond R06 q_i.','R17/R20 mapping pending'),
 c('HC07','Time Window Constraint','Service start b_i satisfies e_i <= b_i <= l_i.','customer/service event','e_i,l_i,b_i','hours from local_day_start_00:00',True,tol['time_s'],'b_i < e_i-tol or b_i > l_i+tol','recompute service-start time in seconds','R07 explicitly defines service-start window.','R17/R20 mapping pending'),
 c('HC08','Time Propagation Constraint','Travel, service, waiting, and charging durations accumulate on one time axis.','route/event','travel_time_s, s_i, waiting, charging','seconds',True,tol['time_s'],'next_time differs from previous + all durations beyond tolerance','recompute every event timestamp','Plan #8; separates waiting/service/charging from road travel.','R17/R20 mapping pending'),
 c('HC09','Operating-Time Constraint','Maximum operating time is enforced only when enabled. Baseline is disabled.','vehicle/route','enabled flag, route duration, maximum time','seconds',False,tol['time_s'],'enabled and route duration > limit + tolerance','read enabled flag; if true compare duration','R10 says maximum_operating_time_enabled=false.','R17/R20 mapping pending; disabled in baseline'),
 c('HC10','Battery / SOC Constraint','SOC never falls below minimum SOC during the route. Baseline minimum is 0.20.','vehicle/route/event','energy, battery, SOC, minimum_soc','SOC ratio [0,1]',True,tol['soc_ratio'],'SOC < 0.20-tolerance','recompute SOC after every travel/charge event','R10 latest SOC semantics.','R17/R20 mapping pending'),
 c('HC11','Initial / Final SOC Constraint','Vehicle starts at SOC 1.00; no independent final target; depot return must still satisfy SOC >= 0.20.','vehicle/depot','initial_soc, minimum_soc, route end SOC','SOC ratio [0,1]',True,tol['soc_ratio'],'initial != 1.00 or return SOC < 0.20-tolerance','check start and depot-return SOC','R10: full departure and return minimum apply.','R17/R20 mapping pending'),
 c('HC12','Charging Constraint','Only R11 adopted stations may be used; each charger visit is an independent charging event. A station may be visited repeatedly, but consecutive charging visits cannot be used to bypass the 30-minute session limit. Effective power is 70 kW, each event duration <=30 min, post-charge SOC <=1.00; access is a modeling assumption. No arbitrary visit-count cap is imposed in R16.','vehicle/charger/event','station IDs, effective power, session limit, SOC, access flag, event sequence','kW/min/kWh/SOC/event sequence',True,tol['energy_kwh'],'unknown station, power<=0, session>30, post_SOC>1, unauthorized consecutive-session bypass, or unassumed access','recompute every event, enforce per-event cap and detect consecutive-session bypass; do not apply customer visit cap to chargers','R11/R15 charging conditions and explicit R16 repeated-visit adoption. QUBO copy limits, if needed, are deferred to R20/R21.','R17/R20 mapping pending; repeated charger visits permitted without R16 count cap'),
 c('HC13','Reachability Constraint','Only accepted reachable R15 arcs may be used; unreachable arcs remain null and cannot enter solver as finite costs.','arc','R15 routing reachable,distance,time','boolean and m/s',True,tol['exact_discrete'],'arc not in accepted reachable set or unreachable arc used','cross-check every route arc against R15 routing','R13/R14 accepted routing semantics.','R17/R20 mapping pending')]
 spec={'constraint_version':'evrp-common-hard-constraints-v1','instance_id':json.loads((instance/'common_instance.json').read_text())['instance_id'],'input_instance_path':str(instance/'common_instance.json'),'input_instance_hash':sha(instance/'common_instance.json'),'solver_independence':True,'discretization_status':'not applied; continuous/base units retained','objective_separation':{'customer_nonvisit_allowed':True,'full_customer_service_is_not_hard_constraint':True,'dfr_maximization':'future objective','distance_tiebreak':'future objective'},'tolerances':tol,'charging_station_revisit_policy':{'status':'RESOLVED','allowed':True,'customer_visit_constraint_applies':False,'each_visit_is_independent_charging_event':True,'consecutive_session_bypass_forbidden':True,'arbitrary_r16_visit_count_cap':False,'qubo_copy_limit_policy':'defer encoding limit to R20 and verify semantic preservation in R21','blocks_pass':False},'constraints':cs,'validator_contract':{'input':'solver-independent route/result plus common instance','output':'per-constraint pass/fail, violation records, checker_status','must_recompute':['customer duplication','depot start/end','flow','subtour','vehicle assignment','capacity','time window','time propagation','operating time','SOC trajectory','initial/final SOC','charging location/power/time','charging revisit/session semantics','reachability'],'charging_revisit_check':'Allow repeated charger events; apply station/power/session/SOC conditions to each event; reject consecutive events that bypass a 30-minute session cap; do not impose an arbitrary count cap in R16.','solver_status_not_authoritative':True,'unsupported_constraint_policy':'If OR-Tools or QUBO cannot represent a constraint, R17/R20/R21 must BLOCKED; never delete it from the common problem.'}}
 (out/'constraint_spec.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n'); (out/'validator_contract.json').write_text(json.dumps(spec['validator_contract'],ensure_ascii=False,indent=2)+'\n'); (out/'constraint_config.json').write_text(json.dumps({'constraint_version':spec['constraint_version'],'instance_id':spec['instance_id'],'enabled_flags':{x['constraint_id']:x['enabled'] for x in cs},'charger_revisit_policy':'RESOLVED_ALLOWED_WITH_SESSION_BYPASS_PROHIBITION'},ensure_ascii=False,indent=2)+'\n'); print(json.dumps({'constraint_version':spec['constraint_version'],'count':len(cs),'charger_revisit_policy':'RESOLVED'},ensure_ascii=False))
if __name__=='__main__': main()
