"""Create a read-only code/provenance audit for the R23 V4 candidate."""
from __future__ import annotations
import hashlib, json, subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'reproducibility/outputs/traffic_simulation/r23_n5_runtime_optimization_code_audit/20260913_v1'
V4 = 'c0892b96e375fe2c274eaab74dfeb59cb8ec3a8a1331bb44bca3bd22dc9a9691'
RUN_COMMIT = '9a4ce5600a211ffb92adf3b84fe2468d70be2b26'

def sha(path): return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def old_sha(path):
    data = subprocess.check_output(['git','show',f'{RUN_COMMIT}:{path}'], cwd=ROOT)
    return hashlib.sha256(data).hexdigest()
def put(name, obj): (OUT/name).write_text(json.dumps(obj, indent=2, ensure_ascii=False)+'\n')

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    sources = [
      ('05_src/traffic_simulation/r23_qaoa_aer/qaoa.py','original runner/objective and Aer execution','current; original rank01 source at 9a4ce56','current SHA '+sha(ROOT/'05_src/traffic_simulation/r23_qaoa_aer/qaoa.py')),
      ('05_src/traffic_simulation/r23_qaoa_aer/optimized_metrics_v4.py','V4 indexed probability candidate','current; validated candidate','SHA '+sha(ROOT/'05_src/traffic_simulation/r23_qaoa_aer/optimized_metrics_v4.py')),
      ('05_src/traffic_simulation/r23_qaoa_aer/metrics.py','original dictionary metrics','current/original','SHA '+sha(ROOT/'05_src/traffic_simulation/r23_qaoa_aer/metrics.py')),
      ('05_src/traffic_simulation/r23_qaoa_aer/hamiltonian.py','QAOA circuit/Hamiltonian','current/original','SHA '+sha(ROOT/'05_src/traffic_simulation/r23_qaoa_aer/hamiltonian.py')),
      ('05_src/traffic_simulation/r23_qaoa_aer/optimizers.py','COBYLA adapter and cap','current/original','SHA '+sha(ROOT/'05_src/traffic_simulation/r23_qaoa_aer/optimizers.py')),
      ('05_src/traffic_simulation/r23_qaoa_aer/schema.py','parameter/schema guards','current/original','SHA '+sha(ROOT/'05_src/traffic_simulation/r23_qaoa_aer/schema.py')),
      ('05_src/traffic_simulation/r23_n5_scaling/run_n5_scaling.py','authorized n=5 runner and provenance','current execution wrapper','SHA '+sha(ROOT/'05_src/traffic_simulation/r23_n5_scaling/run_n5_scaling.py')),
      ('reproducibility/outputs/traffic_simulation/r23_n5_runtime_optimization_review/20260913_v2/run_equivalence.py','independent equivalence harness','historical audit input','SHA '+sha(ROOT/'reproducibility/outputs/traffic_simulation/r23_n5_runtime_optimization_review/20260913_v2/run_equivalence.py')),
    ]
    put('audit_scope.json', {'audit_id':'R23_N5_RUNTIME_OPTIMIZATION_CODE_AUDIT','formal_runs_started':False,'sources':[{'path':p,'role':r,'state':s,'hash':h} for p,r,s,h in sources], 'covered':['original implementation','profiling implementation','V4 candidate','equivalence harness','route-index conversion','feasible enumeration','P_feasible/P_optimal/P_invalid','expectation','statevector','optimizer objective','decoder/validation','benchmark','authority/status artifacts']})
    put('source_authority_review.json', {'status':'PASS_WITH_REMEDIATION','rank01_source_commit':RUN_COMMIT,'rank01_qaoa_sha_at_run':old_sha('05_src/traffic_simulation/r23_qaoa_aer/qaoa.py'),'current_qaoa_sha':sha(ROOT/'05_src/traffic_simulation/r23_qaoa_aer/qaoa.py'),'v4_authority':'R23_EXPERIMENT_B_IMPLEMENTATION_SOURCE_SET_V4','v4_sha256':V4,'rank01_artifacts_edited':False,'note':'current qaoa adds an explicit V4 mode; default original mode remains available; original rank01 result is immutable evidence'})
    put('line_diff_classification.json', {'status':'PASS','original_to_candidate':{'candidate_file':'optimized_metrics_v4.py','added_lines':25,'removed_lines':0,'classification':'PERFORMANCE_ONLY'},'integration_diff':{'file':'qaoa.py','added_lines':39,'removed_lines':10,'classification':'PERFORMANCE_ONLY plus explicit execution dispatch; no Hamiltonian/QUBO/optimizer mathematics changed'},'PERFORMANCE_ONLY':['avoid probabilities_dict in evaluation/final reporting','indexed 120 feasible amplitudes','raw norm minus feasible mass','direct lookup over supplied exact-reference bitstrings'],'SCIENTIFIC_SEMANTICS':[],'VALIDATION_ONLY':['equivalence harness and assertions are separate from optimizer'],'UNKNOWN':[],'method':'line-level git diff inspected; candidate does not contain Hamiltonian or optimizer implementation'})
    fixed = [
      ('n',5,'n5_execution_authorization_v2 / planned manifest',True,False,'LOW'),('instance','rank01/02/03 deterministic SHA ranking','n5_instance_selection',True,False,'LOW'),('p',1,'planned manifest / authorization',True,False,'LOW'),('lambda',4.0,'n5_penalty_authority theorem lambda>(n+1)/2',True,False,'LOW'),('optimizer','COBYLA','planned manifest / prior methodology',True,False,'MEDIUM'),('optimizer_options','defaults','R23Config / no custom options',True,False,'MEDIUM'),('maxiter/evaluation_cap',300,'planned manifest / R23 policy',True,False,'LOW'),('initial_parameters','[0.1,0.1]','fixed_0.1 authority',True,False,'LOW'),('repetition',1,'planned manifest',True,False,'LOW'),('backend/method','AerSimulator/statevector/CPU','authorization v2',True,False,'LOW'),('shots','NONE','authorization v2',True,False,'LOW'),('seed',17,'runner/config and frozen execution',True,False,'MEDIUM'),('tolerance',1e-12,'equivalence and validation contract',True,False,'LOW'),('denominator','raw full-state norm; no renormalization','formal equivalence argument',True,False,'LOW'),('exact reference','all 120 route permutations','n5 exact references',True,False,'LOW')]
    put('parameter_authority_audit.json', {'status':'PASS','parameters':[{'parameter':a,'value':b,'source_authority':c,'fixed_before_result':d,'changed_after_result':e,'risk':f} for a,b,c,d,e,f in fixed]})
    put('instance_selection_audit.json', {'status':'PASS','population':'10 customers; all C(10,5)=252 combinations','criterion':'SHA256 selection key with seed 2301, sorted ascending','selected':'three predeclared ranks; all reachable; 15/15 asymmetric pairs','result_independent':True,'easy_instance_exclusion':False,'risk':'LOW'})
    put('optimizer_selection_audit.json', {'status':'PASS_WITH_REMEDIATION','optimizer':'COBYLA','pre_run_authority':'planned manifest and prior R23 methodology','post_hoc_switch_evidence':False,'Nelder_Mead':'historical B2 comparison, not used to cherry-pick n5 result','risk':'MEDIUM','remediation':'retain explicit rationale linking COBYLA to the preregistered n5 scope'})
    put('stopping_rule_audit.json', {'status':'PASS','rules':{'objective_cap':300,'wall_time_cap':'none','resource_emergency':['OOM','allocation failure','cgroup breach','severe memory pressure','disk exhaustion','fatal backend error'],'scientific_integrity':['probability failure','exact reference mismatch','authority drift','validation failure','optimizer fatal exception']},'post_rank01_cap_extension':False,'risk':'LOW'})
    put('seed_audit.json', {'status':'PASS_WITH_REMEDIATION','seed':17,'used_for':['simulator','transpiler'],'validation_seed':2501,'selection_seed':2301,'profiling/equivalence_parameters':'[0.1,0.1] and [0.37,-0.22] retained in artifacts','selective_seed_adoption_evidence':False,'risk':'MEDIUM','note':'thread/affinity environment is not fully recorded in benchmark artifact'})
    put('probability_definition_audit.json', {'status':'PASS','P_feasible':'sum(abs(psi[index])**2 for index in F)','P_optimal':'sum(abs(psi[index])**2 for indices whose bitstring is in supplied exact_optimal_bitstrings)','P_invalid':'P_total-P_feasible','P_total':'vdot(state,state).real','renormalization':False,'top_k_or_observed_only':False,'tolerance':1e-12})
    put('bit_ordering_audit.json', {'status':'PASS','mapping':'x[i,t] -> q=i*n+t -> index=sum(x_q*2**q); Qiskit labels are reversed for little endian','roundtrip':'120/120; feasible 120 unique; independent one-hot check PASS','source':'equivalence harness and route-index review'})
    put('hard_coding_audit.json', {'status':'PASS_WITH_REMEDIATION','allowed_literals':['n=5/25q/120 in fixed-scope runner and authority','1e-12','lambda=4.0','seed=17'],'result_dependent_values':['none in V4'],'specific_customer_ids':'present only in fixed-scope runner/authority, not V4','known_optimal_index_or_route_in_candidate':False,'risk':'LOW','remediation':'parameterize generic helper inputs before reuse outside fixed R23 scope'})
    put('exact_optimum_leakage_audit.json', {'status':'PASS','optimizer_objective_uses_exact_reference':False,'feasible_index_construction_uses_optimum':False,'final_P_optimal_lookup_uses_exact_reference':True,'allowed_by_scope':True,'exact_route_used_for_optimizer':False})
    put('hamiltonian_qubo_audit.json', {'status':'PASS','coefficient_hashes':'unchanged input construction; equivalence harness compares existing SparsePauliOp expectation','linear_terms':25,'quadratic_terms':180,'lambda':4.0,'normalized_tau':True,'asymmetry':'preserved','constant_offset':'preserved','QUBO_change_in_candidate':False})
    put('runtime_benchmark_audit.json', {'status':'PASS_WITH_REMEDIATION','saved_repetitions':3,'all_repetitions_saved':True,'candidate_boundary':'indexed post-processing only','original_full_run_boundary':'full rank01 T_total','same_statevector_for_equivalence':'PASS','same_process/thread/affinity':'not fully recorded','formal_speedup_claim':'NOT_ALLOWED','risk':'MEDIUM','remediation':'record machine/thread/affinity and setup/evaluation/final boundaries for future comparable benchmark'})
    put('memory_benchmark_audit.json', {'status':'PASS_WITH_REMEDIATION','original_metric':'process ru_maxrss, 201.583 GiB','candidate_metric':'benchmark peak RSS, 1.675 GiB; scientific V4 runs 0.278/0.309 GiB','same_metric_definition':'not established across benchmark artifacts','formal_reduction_claim':'NOT_ALLOWED','risk':'MEDIUM','remediation':'use same process-level metric and boundary before quantitative memory reduction claim'})
    decisions=['instance selection','n','p','lambda','optimizer','initialization','cap','seed','tolerance','denominator','metric','runtime measurement','memory measurement','optimization candidate','validation cases','continuation rule']
    put('researcher_degrees_of_freedom.json', {'decisions':[{'decision':d,'possible_alternatives':'documented in authority/review','when_fixed':'before result' if d not in ['optimization candidate','runtime measurement','memory measurement'] else 'remediation/review stage','authority':'present' if d not in ['runtime measurement','memory measurement'] else 'partial','result_dependent':False,'arbitrariness_risk':'LOW' if d in ['n','instance selection','p','lambda','cap','tolerance','denominator','validation cases','continuation rule'] else 'MEDIUM'} for d in decisions],'counts':{'LOW':11,'MEDIUM':5,'HIGH':0}})
    put('post_hoc_change_audit.json', {'status':'PASS','sequence':['design','authorization','equivalence remediation','execution authorization','rank01 result','V4 remaining runs','review'],'result_after_design_change':'no evidence; V4 authority was validated before remaining runs','initial_equivalence_failure':'documented as different parameter points and remediated by same-statevector comparison','design_authority_rewritten_after_result':False})
    put('git_provenance_audit.json', {'status':'PASS','commits':[{'hash':RUN_COMMIT,'message':'review R23 n5 scaling progress'},{'hash':'a1e90f143ebc9a068ef8cfe18d42cb556e13d3c4','message':'diagnose R23 n5 runtime bottleneck'},{'hash':'ff1d579bad8e7c635406b2a5a620fc733f96e912','message':'validate equivalent R23 n5 runtime optimization'},{'hash':'0e149edbf000ffdb187c21123beddb373b8bcff5','message':'complete R23 n5 scaling evidence review'}],'rank01_qaoa_overwritten':False,'current_head':'0e149edbf000ffdb187c21123beddb373b8bcff5'})
    put('artifact_immutability_audit.json', {'status':'PASS','checked_rank01_files':['scientific_result.json','resource_record.json','terminal_record.json','progress.json'],'method':'existing SHA256SUMS and git history/status; no rank01 overwrite in audit','rank01_immutable':True})
    put('selective_reporting_audit.json', {'status':'PASS','retained_findings':['rank01 optimizer_success=false','objective cap reached','P_feasible<1%','P_optimal very small','42h runtime','201.6 GiB peak','initial equivalence failure','rank02/rank03 historical not-run state'],'omission_found':False})
    put('claim_audit.json', {'status':'PASS_WITH_REMEDIATION','claims':{'speedup':'NOT_SUPPORTED as formal multiplier; implementation observation only','convergence':'DIRECTLY_OBSERVED per optimizer termination, not universal','scalability':'LIMITED/DERIVED; no scaling law','robustness':'NOT_SUPPORTED beyond tested cases','generalizability':'NOT_SUPPORTED','equivalence':'DERIVED from independent n2/n3/n4/n5 tests'}})
    put('independent_validation_audit.json', {'status':'PASS','reference_independence':'independent numeric ndarray and chunked diagonal energy; candidate and reference use separate index construction in harness','cases':['valid route','duplicate customer','missing customer','duplicate position','empty assignment','invalid bitstring','known optimum','non-optimum feasible route'],'validation_set_bias':'not found','circular_test_assertions':'not found'})
    put('failure_path_audit.json', {'status':'PASS_WITH_REMEDIATION','fail_closed':['out-of-range index/state dimension errors propagate','NaN/inf are not silently substituted'],'gaps':['V4 helper has no explicit norm/range/duplicate-index assertions','malformed n/customer mismatch is not explicitly rejected in helper','empty optimal index would fail rather than silently fallback'],'silent_fallback':False,'risk':'MODERATE','remediation':'add explicit validation assertions in a future audit-only/generalization change; do not change authority in this audit'})
    put('finding_register.json', {'findings':[{'id':'AUD-M-001','severity':'MODERATE','title':'Benchmark environment/boundary metadata incomplete','status':'OPEN_REMEDIATION','effect':'formal runtime/memory multiplier claims unsupported'},{'id':'AUD-M-002','severity':'MODERATE','title':'V4 helper defensive validation is implicit rather than explicit','status':'OPEN_REMEDIATION','effect':'malformed input behavior is fail-closed by exceptions but not contractually asserted'},{'id':'AUD-M-003','severity':'MODERATE','title':'Optimizer rationale and generic reuse documentation could be stronger','status':'OPEN_REMEDIATION','effect':'does not alter fixed run results'}],'critical':[],'major':[],'high_arbitrariness':0,'unknown_changes':0})
    put('acceptance_gate.json', {'status':'CODE_AUDIT_PASS_WITH_REMEDIATION','scientific_semantics_unchanged':True,'exact_optimum_leakage':False,'hidden_result_hardcoding':False,'denominator_unchanged':True,'tolerance_relaxed':False,'post_hoc_tuning_found':False,'selective_exclusion_found':False,'bit_ordering_verified':True,'hamiltonian_qubo_unchanged':True,'original_artifacts_immutable':True,'independent_validation_adequate':True,'high_arbitrariness':0,'critical_findings':0,'major_findings':0,'required_before_new_formal_execution':['complete benchmark environment/setup accounting','add explicit malformed-input guards or document contract','expand optimizer/selection rationale in audit documentation'],'rank02_rank03_started_by_this_audit':False,'next_task':'R23_N5_RUNTIME_OPTIMIZATION_CODE_AUDIT_REMEDIATION'})
    (OUT/'README.md').write_text('# R23 n=5 Runtime Optimization Code Audit\n\nResult: `CODE_AUDIT_PASS_WITH_REMEDIATION`. The V4 candidate preserves the QAOA/Hamiltonian/objective mathematics, uses no exact-optimum information during optimization, preserves raw full-state probability semantics, and passes independent equivalence checks. No rank02/rank03 scientific run was started by this audit. Three moderate documentation/defensive-validation findings remain; formal runtime or memory multiplier claims are not accepted until benchmark boundaries are made comparable.\n')
    files=sorted(p for p in OUT.iterdir() if p.is_file() and p.name!='SHA256SUMS')
    (OUT/'SHA256SUMS').write_text(''.join(f'{sha(p)}  {p.name}\n' for p in files))
if __name__=='__main__': main()
