"""Exact, non-QAOA validation utilities for the R20 route-ordering subproblem."""

from .core import (
    ENERGY_ABS_TOLERANCE,
    ExactEnumerationGuardError,
    QuboCoefficients,
    QuboInputError,
    ValidationStatus,
    build_expanded_qubo,
    decode_bitstring,
    encode_route,
    enumerate_qubo_states,
    enumerate_routes,
    evaluate_direct_qubo,
    evaluate_expanded_qubo,
    normalize_travel_time_matrix,
    validate_bitstring,
)
from .routing_adapter import (
    ACCEPTED,
    ADAPTER_VERSION,
    INPUT_SCHEMA_VERSION,
    REJECTED_INCOMPLETE,
    REJECTED_INVALID,
    SOURCE_SCHEMA_VERSION,
    ZERO_TIME_UNRESOLVED,
    adapt_routing_artifact,
    select_customer_ids,
)

__all__ = [
    "ENERGY_ABS_TOLERANCE",
    "ExactEnumerationGuardError",
    "QuboCoefficients",
    "QuboInputError",
    "ValidationStatus",
    "build_expanded_qubo",
    "decode_bitstring",
    "encode_route",
    "enumerate_qubo_states",
    "enumerate_routes",
    "evaluate_direct_qubo",
    "evaluate_expanded_qubo",
    "normalize_travel_time_matrix",
    "validate_bitstring",
    "ACCEPTED",
    "ADAPTER_VERSION",
    "INPUT_SCHEMA_VERSION",
    "REJECTED_INCOMPLETE",
    "REJECTED_INVALID",
    "SOURCE_SCHEMA_VERSION",
    "ZERO_TIME_UNRESOLVED",
    "adapt_routing_artifact",
    "select_customer_ids",
]
