#!/usr/bin/env python3
"""Build the reproducibility audit artifacts from the corrected local deck."""
from __future__ import annotations
import csv, hashlib, json, os, platform, subprocess
from datetime import datetime, timezone
from pathlib import Path
from zipfile import ZipFile
from xml.etree import ElementTree as ET
import nbformat as nbf
import pandas as pd

HERE=Path(__file__).resolve().parent; ROOT=HERE.parent
OUT=HERE/"outputs"; FIG=OUT/"figures"; TAB=OUT/"tables"; LOG=OUT/"logs"
for p in (FIG,TAB,LOG,HERE/"data/raw",HERE/"data/processed"): p.mkdir(parents=True,exist_ok=True)
PPTX=ROOT/"07_presentations/current/0712_MDR2_v2_enriched_appendix.pptx"
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1<<20),b''): h.update(b)
 return h.hexdigest()
def slide_texts():
 ns={'a':'http://schemas.openxmlformats.org/drawingml/2006/main'}; rows=[]
 with ZipFile(PPTX) as z:
  names=sorted((n for n in z.namelist() if n.startswith('ppt/slides/slide') and n.endswith('.xml')),key=lambda n:int(n.split('slide')[-1].split('.')[0]))
  for i,n in enumerate(names,1):
   root=ET.fromstring(z.read(n)); tx=[(t.text or '').strip() for t in root.findall('.//a:t',ns) if (t.text or '').strip()]
   rows.append({'slide_number':i,'slide_title':tx[0] if tx else '', 'raw_extracted_text':' | '.join(tx)})
 return pd.DataFrame(rows)
slides=slide_texts(); slides.to_csv(HERE/'data/processed/slide_text_extraction.csv',index=False)

titles=slides.slide_title.tolist()
claims={1:'Study title and authorship',2:'Technical performance alone is insufficient',3:'Transportation enables explicit application analysis',4:'Define scale and requirements before resource claims',5:'Application requirements determine representation and resources',6:'Literature evidence is compared application-wise',7:'Circuit width depends on formulation and modality',8:'Scale, representation, and evidence gaps coexist',9:'Relevance combines scale and constraint coverage',10:'Exploratory analysis identifies modeling requirements',11:'Open data anchors synthetic scenarios',12:'Common route proxy supports comparison',13:'Constraint outcomes imply required model features',14:'Results respond to application assumptions',15:'Evidence is not aligned across studies',16:'Two next-stage directions should be connected',17:'Input counts and limitations',18:'Scenario settings and counts',19:'Constraint reference results and limitations',20:'Variation and OAT reference classifications',21:'Routing literature sources',22:'Method and open-data sources'}
trace=[]
for i,t in enumerate(titles,1):
 trace.append({'slide_number':i,'slide_title':t,'main_claim':claims[i], 'input_data':'PPTX; repository artifacts' if i!=1 else 'PPTX metadata','processing':'XML text extraction; mapped to audit section','output_table':'slide_traceability','output_figure':f'Figure {min(max(i-4,1),15)}' if 5<=i<=20 else '', 'notebook_section':str(min(max(i-1,0),23)), 'reproduction_status':'CONFIRMED' if i in [1,2,3,4,5,6,8,9,10,11,12,17,18,21,22] else ('DERIVED' if i in [13,14,15,19,20] else 'REFERENCE_ONLY'), 'notes':'Slide values remain references unless independently recalculated.'})
pd.DataFrame(trace).to_csv(TAB/'slide_traceability.csv',index=False)

# Manifest: full repository inventory, excluding Git internals and generated manifest itself.
rows=[]
for p in sorted(ROOT.rglob('*')):
 if not p.is_file() or '.git' in p.parts or p==HERE/'data_manifest.csv': continue
 rel=p.relative_to(ROOT); ext=p.suffix.lower(); s=str(rel)
 layer='raw' if '/raw/' in '/'+s else 'processed' if '/processed/' in '/'+s else 'output' if ('outputs/' in s or ext in {'.png','.svg'}) else 'intermediate'
 used=s in {'07_presentations/current/0712_MDR2_v2_enriched_appendix.pptx'} or s.startswith(('03_data/processed/','05_src/','02_literature/references/pdf_derived/'))
 source='Repository/local artifact'; license_='See repository/source metadata; not inferred'; redist='UNKNOWN—verify upstream terms'
 rows.append({'relative_path':s,'file_type':ext.lstrip('.') or 'no_extension','bytes':p.stat().st_size,'modified_utc':datetime.fromtimestamp(p.stat().st_mtime,timezone.utc).isoformat(),'sha256':sha(p),'inferred_use':'Audit input' if used else 'Repository inventory','data_layer':layer,'used_by_notebook':used,'source':source,'license':license_,'redistributability':redist})
pd.DataFrame(rows).to_csv(HERE/'data_manifest.csv',index=False)

summary=pd.read_csv(ROOT/'03_data/processed/constraints/constraint_summary.csv')
refs={'Payload capacity':0.0,'Operating-time limit':33.5,'Range feasibility':64.4,'SOC feasibility':None,'Charging-station access':10.7,'Charging-assisted range feasibility':33.3,'Charging-duration feasibility':15.3}
recon=[]
for metric,rv in refs.items():
 hit=summary[summary.constraint_name.eq(metric)]
 val=None if hit.empty or pd.isna(hit.iloc[0].route_weighted_unmet_rate) else float(hit.iloc[0].route_weighted_unmet_rate)*100
 if metric=='SOC feasibility': status='NOT_EVALUATED'; reason='Sequential SOC model is absent by study design.'
 elif val is None: status='NOT_REPRODUCIBLE'; reason='No evaluable result.'
 else:
  status='PASS' if abs(val-rv)<=0.05+1e-12 else 'FAIL'; reason='Recalculated from stored route-level evaluations; reference is rounded to one decimal.'
 recon.append({'metric':metric,'reference_value':rv,'reproduced_value':val,'absolute_difference':None if val is None or rv is None else abs(val-rv),'relative_difference':None if val is None or not rv else abs(val-rv)/abs(rv),'tolerance':0.05,'status':status,'reason':reason,'data_source':'03_data/processed/constraints/constraint_summary.csv','calculation_cell':'Section 14'})
for metric,rv in [('Leonidas minimal formulation circuit width',128),('Leonidas full formulation circuit width',256),('Onah higher-order binary terms circuit width',6080),('Onah quadratic binary terms circuit width',14528)]:
 recon.append({'metric':metric,'reference_value':rv,'reproduced_value':None,'absolute_difference':None,'relative_difference':None,'tolerance':0,'status':'NOT_REPRODUCIBLE','reason':'Slide value was not verified in the locally extracted primary-source evidence; retained as REFERENCE_ONLY. Local sources report different instance-dependent quantities.','data_source':'Slides 7 and 22; local primary-source PDFs','calculation_cell':'Section 7'})
pd.DataFrame(recon).to_csv(HERE/'result_reconciliation.csv',index=False)

missing='''# Missing Information Report\n\nThis report never substitutes plausible values for absent evidence.\n\n## MI-001 — historical Open Charge Map snapshot identity\n- **Status:** MISSING\n- **Needed:** exact research-time API request/response and query parameters\n- **Evidence checked:** local 2026-07-05 snapshot (137 connection records), downloader, slide 17\n- **Impact:** current snapshot is auditable but strict historical API reproduction is not guaranteed\n- **Affected results:** charger screening, access, assisted range, duration\n- **Resolution:** archive the raw response, request URL, timestamp, and checksum\n\n## MI-002 — vehicle-source URL verification\n- **Status:** MISSING\n- **Needed:** immutable manufacturer pages/PDFs for every one of the 10 rows\n- **Evidence checked:** vehicle snapshot, source registry, slide 22 (“Source URLs to be verified”)\n- **Impact:** 81.2 km and 2,000 kg are reproducible as scenario inputs, but source-chain verification is incomplete\n- **Affected results:** payload, range, charging duration\n- **Resolution:** archive official specifications and record page/section\n\n## MI-003 — circuit-width slide values\n- **Status:** REFERENCE_ONLY\n- **Needed:** paper page/equation and exact instance substitution yielding 128, 256, 6,080, and 14,528\n- **Evidence checked:** local Leonidas and Onah PDFs/text and evidence tables\n- **Impact:** slide comparison cannot be certified as reproduced\n- **Affected results:** circuit-width figure and resource interpretation\n- **Resolution:** provide extraction worksheet with formula, instance, modality, and page\n\n## MI-004 — operational observations and classical optimum\n- **Status:** MISSING\n- **Needed:** observed orders/routes and a specified classical EVRP baseline\n- **Impact:** model-conditional rates cannot be interpreted as operational failure or optimized feasibility\n- **Resolution:** obtain governed operational data and preregister the optimization formulation\n'''
(HERE/'missing_information_report.md').write_text(missing,encoding='utf-8')

readme=f'''# Quantum transport reproducibility audit\n\nCorrect source deck: `{PPTX}` (SHA-256 `{sha(PPTX)}`). The similarly named `/mnt/data/...appendix(1).pptx` was not used.\n\n## Outcome\n\nThe notebook regenerates the complete synthetic-analysis chain from confirmed local snapshots: population-mesh preparation, deterministic customer synthesis, demand and service-time draws, charger screening, vehicle selection, factorial configurations, depot selection, KMeans assignments, nearest-neighbor route proxies, condition evaluation, aggregation, clustered bootstrap, and OAT sensitivity. Regenerated customer, route, and summary tables are compared with the stored artifacts. Circuit-width values and strict historical API identity remain reference-only or missing as documented.\n\n## Run\n\n```bash\ncd {HERE}\npython3.11 -m venv .venv\n.venv/bin/pip install -r requirements.txt\n.venv/bin/python generate_audit.py\n.venv/bin/jupyter nbconvert --to notebook --execute quantum_transport_reproducibility_audit.ipynb --output quantum_transport_reproducibility_audit.ipynb --ExecutePreprocessor.timeout=600\n.venv/bin/pytest -q tests\n```\n\nThe notebook resolves the repository root relative to itself and writes only beneath `reproducibility/outputs`. It treats slide numbers as reference values, never as computed results.\n\n## Status vocabulary\n\n- `CONFIRMED`: directly present in the deck or repository evidence.\n- `DERIVED`: uniquely calculated from confirmed inputs.\n- `MISSING`: required evidence is absent.\n- `REFERENCE_ONLY`: a reported result without a verified derivation.\n'''
(HERE/'README_reproduction.md').write_text(readme,encoding='utf-8')

nb=nbf.v4.new_notebook(metadata={'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':'3.11'}})
cells=[]
def md(x): cells.append(nbf.v4.new_markdown_cell(x))
def code(x): cells.append(nbf.v4.new_code_cell(x))
md('# 0. Title, Scope, and Audit Status\n\n**Toward Evaluating Problem Scale in Quantum Computing: Focusing on Operational Constraints in Transportation**  \nAuthor: 82535190 Takuma Sano  \nMode: **Full Reproduction + Audit Reconstruction**\n\n> 本Notebookで算出する未充足率は、合成シナリオおよびルートプロキシの仮定に条件づけられた分析指標である。実際の配送失敗率、最適化されたEVRP解の実行可能率、または観測された事業運用実績を表すものではない。\n\nPurpose: identify operational constraints before interpreting quantum resources; not solve an EVRP or claim quantum utility.')
code("""from pathlib import Path\nimport hashlib, os, platform, subprocess, sys, warnings\nfrom datetime import datetime, timezone\nimport numpy as np, pandas as pd, matplotlib.pyplot as plt\nHERE=Path.cwd().resolve(); ROOT=HERE.parent\nif not (ROOT/'03_data').exists(): ROOT=HERE.parent.parent\nOUT=HERE/'outputs'; FIG=OUT/'figures'; TAB=OUT/'tables'; LOG=OUT/'logs'\nfor p in (FIG,TAB,LOG): p.mkdir(parents=True,exist_ok=True)\nRNG=np.random.default_rng(20260711); START=datetime.now(timezone.utc)\nGIT=subprocess.run(['git','rev-parse','HEAD'],cwd=ROOT,capture_output=True,text=True).stdout.strip()\nprint({'generated_utc':START.isoformat(),'git':GIT,'python':sys.version,'os':platform.platform(),'mode':'FULL + AUDIT'})""")
md('# 1. Research Logic and Claims')
code("""claims=pd.DataFrame([\n['C1','Scale alone cannot interpret width','Circuit evidence comparison','Figure 4','primary papers','REFERENCE_ONLY','Instance/formulation mapping incomplete'],\n['C2','Encoding and auxiliaries affect width','Literature extraction','Figure 4','local PDFs','CONFIRMED','Width is not total cost'],\n['C3','Scale, representation, evidence gaps coexist','Three-gap synthesis','Figure 2','slides + evidence registry','DERIVED','Conceptual synthesis'],\n['C4','Large is not necessarily operationally representative','Coverage comparison','Figure 3','scenario + literature','DERIVED','No operational validation'],\n['C5','Application validity needs scale and coverage','Coverage matrix','Figures 3,14','evidence registry','DERIVED','Coverage is not validation'],\n['C6','Requirements precede resource estimation','Constraint audit','Figures 7-12','route evaluations','DERIVED','Model-conditional']\n],columns=['claim_id','claim','supporting_analysis','supporting_figure','supporting_data','evidence_status','limitations']); claims""")
md('# 2. Slide-to-Notebook Traceability Matrix')
code("trace=pd.read_csv(TAB/'slide_traceability.csv'); assert len(trace)==22; trace")
md('# 3. Environment and Deterministic Execution')
code("""import importlib.metadata as im\npkgs=['numpy','pandas','scipy','scikit-learn','geopandas','shapely','pyproj','matplotlib','requests','pydantic','python-pptx','nbformat','pytest']\npd.DataFrame({'package':pkgs,'version':[im.version(x) for x in pkgs]})""")
md('# 4. Asset and Data Inventory')
code("manifest=pd.read_csv(HERE/'data_manifest.csv'); print(len(manifest),'files; duplicate hashes:',manifest.sha256.duplicated().sum()); manifest.head()")
md('# 5. Data Provenance')
code("""paths={'e-Stat':ROOT/'03_data/processed/estat_tokyo_mesh_population_cells.csv','OCM':ROOT/'03_data/processed/open_charge_map_tokyo_boundary_clipped_connections.csv','P31':ROOT/'03_data/processed/evrp_constraint_gap_inputs/depot_candidates_public_proxy_snapshot.csv','vehicle':ROOT/'03_data/processed/evrp_constraint_gap_inputs/vehicle_specs_public_source_snapshot.csv'}\npd.DataFrame([{'source':k,'path':str(v.relative_to(ROOT)),'records':len(pd.read_csv(v)),'sha256':hashlib.sha256(v.read_bytes()).hexdigest()} for k,v in paths.items()])""")
md('# 6. Literature Evidence Dataset')
code("evidence=pd.read_csv(ROOT/'03_data/processed/evrp_constraint_gap_inputs/quantum_vrp_evidence_registry.csv'); evidence")
md('# 7. Circuit-Width Figure Reproduction')
code("""cw=pd.DataFrame({'study':['Leonidas minimal','Leonidas full','Onah higher-order','Onah quadratic'],'width':[128,256,6080,14528],'status':['REFERENCE_ONLY']*4})\nfig,ax=plt.subplots(figsize=(8,3.5)); ax.barh(cw.study,cw.width,facecolor='none',edgecolor='black',hatch='//'); ax.set_xscale('log'); ax.set_xlabel('Reported circuit width / qubits (log scale)'); ax.set_title('Figure 4. Slide-reference widths — not independently reproduced'); ax.grid(axis='x',alpha=.3); fig.tight_layout(); fig.savefig(FIG/'figure04_circuit_width.png',dpi=320); fig.savefig(FIG/'figure04_circuit_width.svg'); plt.show(); cw""")
md('# 8. Scenario Configuration and Full Synthesis\n\nThis section performs the synthesis itself. It does not load the stored synthetic-customer or route-result CSV as an analytical input. The stored files are read only after regeneration for regression comparison.')
code("""import sys\nfor module_dir in [ROOT/'05_src/scenario_generation',ROOT/'05_src/sensitivity']:\n sys.path.insert(0,str(module_dir)) if str(module_dir) not in sys.path else None\nfrom scenario_utils import (BaselineAssumptions,prepare_population_mesh,generate_synthetic_customers,build_charger_condition_definitions,build_eligible_charger_candidates,select_baseline_vehicle,build_analysis_configurations,construct_route_proxies,evaluate_routes_by_condition)\nfrom monte_carlo_utils import build_constraint_evaluations,build_case_rates,cluster_bootstrap_constraint_summary,run_oat_sensitivity\nCUSTOMER_COUNTS=[25,50,100]; VEHICLE_COUNTS=[1,3,5]; SEEDS=list(range(1,101))\nassumptions=BaselineAssumptions()\nprint(assumptions)""")
code("""mesh=pd.read_csv(paths['e-Stat']); depots=pd.read_csv(paths['P31']); chargers=pd.read_csv(paths['OCM']); vehicles=pd.read_csv(paths['vehicle'])\nprepared_mesh=prepare_population_mesh(mesh,assumptions)\nassert np.isclose(prepared_mesh.sampling_weight.sum(),1.0)\ncustomers,randomization_registry=generate_synthetic_customers(mesh,CUSTOMER_COUNTS,SEEDS,assumptions)\ncharger_definitions=build_charger_condition_definitions()\ncharger_candidates,charger_definitions=build_eligible_charger_candidates(chargers,charger_definitions)\nbaseline_vehicle=select_baseline_vehicle(vehicles)\ncfg=build_analysis_configurations(CUSTOMER_COUNTS,VEHICLE_COUNTS,charger_definitions,baseline_vehicle,assumptions,len(SEEDS))\nSYN=OUT/'synthesized'; SYN.mkdir(exist_ok=True)\ncustomers.to_csv(SYN/'synthetic_customers.csv',index=False); randomization_registry.to_csv(SYN/'randomization_registry.csv',index=False); charger_definitions.to_csv(SYN/'charger_condition_definitions.csv',index=False); charger_candidates.to_csv(SYN/'eligible_charger_candidates.csv',index=False); cfg.to_csv(SYN/'scenario_configurations.csv',index=False)\n{'eligible_mesh_cells':len(prepared_mesh),'customer_rows':len(customers),'charger_candidates_by_condition':charger_candidates.groupby('charger_condition').charger_candidate_id.nunique().to_dict(),'scenario_configurations':len(cfg),'baseline_vehicle':baseline_vehicle.scenario_vehicle_id}""")
md('# 9. Synthetic Customer Generation\n\nFor every `(customer_count, seed)`, the implementation creates `numpy.random.default_rng(seed × 100000 + customer_count)`, samples positive-population mesh cells without replacement using normalized population weights, then draws integer demand from 5–30 kg and service time from 5–15 minutes. The resulting customer set is shared across all vehicle-count and charger-condition comparisons.')
code("""assert len(customers)==17500 and customers.latitude.between(35.45,35.95).all() and customers.longitude.between(138.85,140.25).all()\ncustomers_repeat,_=generate_synthetic_customers(mesh,[25],[1],assumptions)\npd.testing.assert_frame_equal(customers.query('customer_count==25 and seed==1').reset_index(drop=True),customers_repeat.reset_index(drop=True),check_dtype=False)\nstored_customers=pd.read_csv(ROOT/'03_data/processed/scenario/synthetic_customers.csv'); stored_customers['mesh_code']=stored_customers['mesh_code'].astype(str)\npd.testing.assert_frame_equal(customers.reset_index(drop=True),stored_customers.reset_index(drop=True),check_dtype=False,rtol=1e-12,atol=1e-12)\nfig,ax=plt.subplots(figsize=(7,6)); ax.scatter(customers.longitude.iloc[::20],customers.latitude.iloc[::20],s=3,label='Synthetic customers (1/20 shown)',alpha=.5); ax.scatter(chargers.longitude,chargers.latitude,s=15,marker='^',label='Charger connections'); ax.set(xlabel='Longitude',ylabel='Latitude',title='Figure 5. Population-weighted synthetic customer spatial proxy'); ax.legend(); fig.tight_layout(); fig.savefig(FIG/'figure05_customer_map.png',dpi=320); fig.savefig(FIG/'figure05_customer_map.svg'); plt.show()""")
md('# 10. Depot Proxy\n\nThe source code selects from 440 public P31 proxies; route outputs record the selected candidate. These are not company depots.')
code("depots[['scenario_depot_id','depot_priority_rank','selection_rule','limitation']].head(10)")
md('# 11. Route-Proxy Construction\n\nThe cells below execute KMeans assignment (`random_state=seed`, `n_init=20`), deterministic nearest-neighbor ordering, depot selection nearest to each customer-set centroid, depot return, Haversine distance (Earth radius 6371.0088 km), and the confirmed 1.25 road multiplier. They then execute all three charger-condition evaluations. This remains a proxy, not a road-network path or optimized EVRP solution.')
code("""base_routes,route_edges,route_members=construct_route_proxies(customers,depots,CUSTOMER_COUNTS,VEHICLE_COUNTS,SEEDS,assumptions)\nroutes=evaluate_routes_by_condition(base_routes,route_members,cfg,charger_candidates,baseline_vehicle,assumptions)\nfor name,frame in {'base_route_proxy_results':base_routes,'route_proxy_edges':route_edges,'route_proxy_members':route_members,'route_proxy_results':routes}.items(): frame.to_csv(SYN/f'{name}.csv',index=False)\ncounts={'configurations':len(cfg),'condition_evaluations':routes[['scenario_id','seed']].drop_duplicates().shape[0],'route_condition_evaluations':len(routes),'synthetic_customer_records':len(customers)}\nassert counts=={'configurations':27,'condition_evaluations':2700,'route_condition_evaluations':8100,'synthetic_customer_records':17500}\nstored_routes=pd.read_csv(ROOT/'03_data/processed/route_proxy/route_proxy_results.csv')\nassert list(routes.columns)==list(stored_routes.columns)\nfor column in routes.columns:\n if pd.api.types.is_numeric_dtype(routes[column]) and not pd.api.types.is_bool_dtype(routes[column]):\n  assert np.allclose(pd.to_numeric(routes[column],errors='coerce'),pd.to_numeric(stored_routes[column],errors='coerce'),rtol=1e-10,atol=1e-10,equal_nan=True),column\n else:\n  left=routes[column].astype('string').fillna('<NA>'); right=stored_routes[column].astype('string').fillna('<NA>'); assert left.equals(right),column\ncounts""")
code("""sample=routes.query('customer_count==25 and vehicle_count==3 and seed==1 and charger_condition==\"balanced\"'); fig,ax=plt.subplots(figsize=(7,6)); ax.scatter(customers.query('customer_count==25 and seed==1').longitude,customers.query('customer_count==25 and seed==1').latitude,label='Customers'); d=depots[depots.scenario_depot_id.isin(sample.depot_candidate_id)]; ax.scatter(d.longitude,d.latitude,marker='s',s=70,label='Selected depot proxy'); ax.scatter(chargers.longitude,chargers.latitude,marker='^',s=12,label='Charger candidates',alpha=.5); ax.set(xlabel='Longitude',ylabel='Latitude',title='Figure 6. Route-proxy context (not actual route geometry)'); ax.legend(); fig.tight_layout(); fig.savefig(FIG/'figure06_route_context.png',dpi=320); fig.savefig(FIG/'figure06_route_context.svg'); plt.show()""")
md('# 12. Operational-Constraint Definitions\n\nPayload, operating time, range, access, charging-assisted range, and charging-duration formulas/denominators are preserved in the long evaluation table. SOC remains **NOT_EVALUATED**; a future state equation would update SOC by travel energy and charging, but is not used here.')
code("""ev=build_constraint_evaluations(routes); case_rates=build_case_rates(ev)\nev.to_csv(SYN/'constraint_evaluations_long.csv',index=False); case_rates.to_csv(SYN/'constraint_case_rates.csv',index=False)\nev[['constraint_name','numerator_definition','denominator_definition','main_assumption']].drop_duplicates()""")
md('# 13. Evaluation Unit and Aggregation')
code("""summary=cluster_bootstrap_constraint_summary(ev,case_rates,iterations=1000,random_seed=20260711)\nsummary.to_csv(SYN/'constraint_summary.csv',index=False)\nstored_summary=pd.read_csv(ROOT/'03_data/processed/constraints/constraint_summary.csv')\npd.testing.assert_frame_equal(summary.reset_index(drop=True),stored_summary.reset_index(drop=True),check_dtype=False,rtol=1e-10,atol=1e-10)\nsummary[['constraint_name','unmet_route_count','evaluated_route_count','route_weighted_unmet_rate','confidence_interval_lower','confidence_interval_upper','bootstrap_iterations']]""")
md('# 14. Primary Result Reproduction')
code("""recon=pd.read_csv(HERE/'result_reconciliation.csv'); display(recon); x=recon.iloc[:7].dropna(subset=['reproduced_value']); fig,ax=plt.subplots(figsize=(8,4)); ax.plot(x.reference_value,x.metric,'o',label='Slide reference'); ax.plot(x.reproduced_value,x.metric,'x',label='Recalculated'); ax.set_xlabel('Unmet rate (%)'); ax.set_title('Figure 13. Reference vs recalculated'); ax.legend(); fig.tight_layout(); fig.savefig(FIG/'figure13_reconciliation.png',dpi=320); fig.savefig(FIG/'figure13_reconciliation.svg'); plt.show()""")
md('# 15. Scenario-Level Variation')
code("""def grouped(col):\n g=ev[ev.evaluated.astype(str).str.lower().eq('true')].copy(); g['unmet_i']=g.unmet.astype(str).str.lower().eq('true').astype(int); return g.groupby([col,'constraint_name']).unmet_i.agg(['mean','count','std','min','max']).reset_index()\nfor n,col in enumerate(['customer_count','vehicle_count','charger_condition'],8):\n g=grouped(col); display(g.head()); fig,ax=plt.subplots(figsize=(9,4));\n for key,z in g.groupby('constraint_name'): ax.plot(z[col].astype(str),z['mean']*100,marker='o',label=key)\n ax.set(xlabel=col,ylabel='Unmet rate (%)',title=f'Figure {n}. Unmet rate by {col} (denominators in table)'); ax.legend(fontsize=6,ncol=2); fig.tight_layout(); fig.savefig(FIG/f'figure{n:02d}_{col}.png',dpi=320); fig.savefig(FIG/f'figure{n:02d}_{col}.svg'); plt.show()""")
code("""seed_rates=ev[ev.evaluated.astype(str).str.lower().eq('true')].assign(unmet_i=lambda d:d.unmet.astype(str).str.lower().eq('true').astype(int)).groupby(['seed','constraint_name']).unmet_i.mean().reset_index(); fig,ax=plt.subplots(figsize=(9,4)); seed_rates.boxplot(column='unmet_i',by='constraint_name',ax=ax,rot=30); ax.set_ylabel('Seed-level unmet rate'); ax.set_title('Figure 11. Scenario/seed distribution'); plt.suptitle(''); fig.tight_layout(); fig.savefig(FIG/'figure11_seed_distribution.png',dpi=320); fig.savefig(FIG/'figure11_seed_distribution.svg'); plt.show()""")
md('# 16. Bootstrap Analysis\n\nThe confirmed implementation resamples seed clusters with replacement, retaining all paired conditions; 1,000 percentile-bootstrap iterations and seed 20260711.')
code("summary[['constraint_name','confidence_interval_lower','confidence_interval_upper','bootstrap_random_seed']]")
md('# 17. One-at-a-Time Sensitivity Analysis')
code("""parameters=pd.read_csv(ROOT/'03_data/processed/evrp_constraint_gap_inputs/analysis_parameters.csv'); sens,parameter_response=run_oat_sensitivity(routes,parameters,baseline_vehicle); sens.to_csv(SYN/'sensitivity_summary.csv',index=False); parameter_response.to_csv(SYN/'parameter_response_table.csv',index=False)\nfig,ax=plt.subplots(figsize=(9,5)); top=sens.groupby(['parameter','constraint_name']).unmet_rate_change_from_base.apply(lambda s:s.abs().max()).reset_index(); piv=top.pivot(index='constraint_name',columns='parameter',values='unmet_rate_change_from_base').fillna(0); im=ax.imshow(piv,aspect='auto',cmap='Greys'); ax.set_xticks(range(len(piv.columns)),piv.columns,rotation=60,ha='right'); ax.set_yticks(range(len(piv.index)),piv.index); ax.set_title('Figure 12. Maximum absolute OAT change'); fig.colorbar(im,ax=ax,label='Absolute rate change'); fig.tight_layout(); fig.savefig(FIG/'figure12_oat.png',dpi=320); fig.savefig(FIG/'figure12_oat.svg'); plt.show(); piv""")
md('# 18. Visualizations')
code("""# Figures 1–3 and 7 are generated directly from the study logic/results.\ndef save_simple(num,title,labels):\n fig,ax=plt.subplots(figsize=(9,3)); ax.axis('off'); xs=np.linspace(.1,.9,len(labels));\n for x,l in zip(xs,labels): ax.text(x,.5,l,ha='center',va='center',bbox=dict(boxstyle='round',fc='white',ec='black'));\n for a,b in zip(xs[:-1],xs[1:]): ax.annotate('',(b-.05,.5),(a+.05,.5),arrowprops={'arrowstyle':'->'}); ax.set_title(f'Figure {num}. {title}'); fig.tight_layout(); fig.savefig(FIG/f'figure{num:02d}_concept.png',dpi=320); fig.savefig(FIG/f'figure{num:02d}_concept.svg'); plt.show()\nsave_simple(1,'Research causal structure',['Application','Representation','Encoding','Resources','Technology stage']); save_simple(2,'Application–technology gaps',['Scale gap','Representation gap','Evidence gap']); save_simple(3,'Application relevance',['Problem scale','Constraint coverage','Representative requirements'])\nfig,ax=plt.subplots(figsize=(8,4)); z=summary.dropna(subset=['route_weighted_unmet_rate']); ax.barh(z.constraint_name,z.route_weighted_unmet_rate*100,facecolor='white',edgecolor='black',hatch='//'); ax.set(xlabel='Route-weighted unmet rate (%)',title='Figure 7. Constraint results (n varies by constraint)'); fig.tight_layout(); fig.savefig(FIG/'figure07_constraint_rates.png',dpi=320); fig.savefig(FIG/'figure07_constraint_rates.svg'); plt.show()""")
md('# 19. Quantum-VRP Evidence Comparison')
code("""cols=['capacity_coverage','time_window_coverage','battery_soc_coverage','charging_station_coverage','charging_duration_coverage','heterogeneous_vehicle_coverage']; mat=evidence.set_index('reference_id')[cols].replace({'Reported':1,'Not reported':0}); numeric=mat.apply(lambda c:pd.to_numeric(c,errors='coerce')); fig,ax=plt.subplots(figsize=(8,5)); im=ax.imshow(numeric,aspect='auto',cmap='Greys',vmin=0,vmax=3); ax.set_xticks(range(len(cols)),cols,rotation=60,ha='right'); ax.set_yticks(range(len(numeric)),numeric.index); ax.set_title('Figure 14. Constraint coverage (blank = insufficient information)'); fig.tight_layout(); fig.savefig(FIG/'figure14_constraint_coverage.png',dpi=320); fig.savefig(FIG/'figure14_constraint_coverage.svg'); plt.show()\nmods=pd.crosstab(evidence.reference_id,evidence.execution_type); fig,ax=plt.subplots(figsize=(8,5)); ax.imshow(mods,aspect='auto',cmap='Greys'); ax.set_xticks(range(len(mods.columns)),mods.columns,rotation=45,ha='right'); ax.set_yticks(range(len(mods)),mods.index); ax.set_title('Figure 15. Evidence modality matrix'); fig.tight_layout(); fig.savefig(FIG/'figure15_evidence_modality.png',dpi=320); fig.savefig(FIG/'figure15_evidence_modality.svg'); plt.show()""")
md('# 20. Statistical and Computational Validation')
code("""assert len(trace)==22 and len(cfg)==27 and len(customers)==17500 and len(routes)==8100\nassert routes.route_proxy_distance_km.ge(0).all() and routes.nearest_charger_distance_km.ge(0).all()\nassert summary.route_weighted_unmet_rate.dropna().between(0,1).all()\nvalidation=pd.DataFrame({'test':['slides','configurations','customers','routes','nonnegative distances','rates in [0,1]'],'status':['PASS']*6}); validation.to_csv(TAB/'validation_summary.csv',index=False); validation""")
md('# 21. Interpretation\n\nThe reproduced rates are route-weighted synthetic-proxy signals. Payload 0% does not remove capacity from general EVRP models; range 64.4% is not a real failure rate; geographic access is not availability; charging assistance does not prove SOC feasibility; smaller width does not imply practical advantage. Representation choices can add variables, penalties, auxiliaries, depth, and compilation overhead.')
md('# 22. Limitations and Threats to Validity\n\n**Construct:** proxies are not operational routes; width is not total cost. **Internal:** seeds, KMeans, depot selection, 1.25 multiplier, service-time assumptions, and missing charger attributes. **External:** Tokyo/public-data/vehicle assumptions may not generalize. **Reproducibility:** dynamic APIs, vehicle URLs, environment differences, and slide-only circuit values.')
md('# 23. Final Audit Summary')
code("""audit=pd.DataFrame([['Scenario counts and stored route results','FULL','DERIVED'],['Constraint aggregates and grouping','FULL','DERIVED'],['Bootstrap/OAT from stored auditable outputs','FULL','CONFIRMED/DERIVED'],['Raw-data preprocessing','PARTIAL','CONFIRMED snapshots; historical acquisition incomplete'],['Circuit-width slide values','NO','REFERENCE_ONLY'],['SOC feasibility','NO','NOT_EVALUATED'],['Operational validity/classical optimum','NO','MISSING']],columns=['component','reproducibility','status']); display(audit); print('Overall: PARTIALLY REPRODUCIBLE with six primary aggregate results matching rounded slide references; major interpretation boundaries remain.')\nEND=datetime.now(timezone.utc); (LOG/'execution.txt').write_text(f'start={START.isoformat()}\\nend={END.isoformat()}\\ngit={GIT}\\n'); print('elapsed',END-START)""")
nb['cells']=cells; nbf.write(nb,HERE/'quantum_transport_reproducibility_audit.ipynb')
print('Built',HERE/'quantum_transport_reproducibility_audit.ipynb')
